spring:
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=4s
    cache-names: currency
# H2 properties
  datasource:
    url: jdbc:h2:mem:jpa_jbd
    driverClassName: org.h2.Driver
    username: shyam
    password: shyam
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2