DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY (
  COUNTRY_CODE VARCHAR(5) PRIMARY KEY,
  COUNTRY VARCHAR(250) NOT NULL,
  CURRENCY_CODE VARCHAR(3) NOT NULL
);

INSERT INTO CURRENCY (CURRENCY_CODE, COUNTRY_CODE, COUNTRY) VALUES
  ('USD', 'US', 'USA'),
  ('CAD', 'CA', 'Canada'),
  ('INR', 'IN', 'India');